- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs 
    state: installed

- name: Add Applications User
  ansible.builtin.user:
    name: roboshop

- name: Remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app Directory
  ansible.builtin.file:
    name: /app   
    state: directory

- name: Download {{componment}} App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes