- name: Install Maven
  ansiable.builtin.yum:
    name: maven
    state: install

- name: App Pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Maven Build
  ansible.builtin.shell: mvn clean package
  args:
    chdir: /app  

- name: systemD Setup
  ansible.builtin.include_tasks: "systemd.yml"    

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load  