- name: Load MySQL Schema
  community.mysql.mysql._db
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: mysql-dev.devopsk24.online
    login_user: root
    login_passowrd: "{{root_mysql_password}}" 
  
